export const servicesCard = [
  {
    id: 1,
    icon: "/images/mobile.png",
    title: "Mobile Application",
    desc: "Application development refers to the process of designing, creating, and testing software",
    url: "/services/mobile",
  },

  {
    id: 2,
    icon: "/images/Web.png",
    title: "Web Application",
    desc: "Web development is a crucial aspect of any modern digital project It involves creating a user-friendly",
    url: "/services/web",
  },
  {
    id: 3,
    icon: "/images/digital.png",
    title: "Digital Transformation",
    desc: "Digital transformation refers to the process of leveraging digital technologies and innovations",
    url: "/services/digital",
  },
  {
    id: 4,
    icon: "/images/product.png",
    title: "Product Prototyping",
    desc: "Product prototyping is the process of creating a functional or non-functional model of a product",
    url: "/services/product",
  },
];

export const clientLogo = [
  {
    id: 1,
    img: "/images/muncipal.png",
    alt: "Muncipal Logo",
  },
  {
    id: 2,
    img: "/images/geci.png",
    alt: "GEC India Logo",
  },
  {
    id: 3,
    img: "/images/lijjat.png",
    alt: "Lijjat Logo",
  },
  {
    id: 4,
    img: "/images/lehnaar.png",
    alt: "Lehnaar Logo",
  },
  {
    id: 5,
    img: "/images/mda.png",
    alt: "MDA Logo",
  },
  {
    id: 6,
    img: "/images/euro_detnal.png",
    alt: "Euro Dental Logo",
  },
];

export const technologiesIcons = [
  {
    id: 1,
    img: "/images/reactclinet.png",
    title: "React Js",
    url: "/technology/react",
  },
  {
    id: 2,
    img: "/images/next.png",
    title: "Next Js",
    url: "/technology/next",
  },
  {
    id: 3,
    img: "/images/node.png",
    title: "Node Js",
    url: "/technology/node",
  },
  {
    id: 4,
    img: "/images/php.png",
    title: "PHP",
    url: "/technology/php",
  },
  {
    id: 5,
    img: "/images/ios.png",
    title: "IOS",
    url: "/technology/ios",
  },
  {
    id: 6,
    img: "/images/android.png",
    title: "Android",
    url: "/technology/android",
  },
  {
    id: 7,
    img: "/images/vue.png",
    title: "Vue Js",
    url: "/technology/vue",
  },

  {
    id: 8,
    img: "/images/flutter.png",
    title: "Flutter",
    url: "/technology/flutter",
  },
  {
    id: 9,
    img: "/images/wordpress.png",
    title: "Wordpress",
    url: "/technology/wordpress",
  },
  {
    id: 10,
    img: "/images/meganto.png",
    title: "Magneto",
    url: "/technology/magento",
  },
  {
    id: 11,
    img: "/images/wocommerce.png",
    title: "Wocommerce",
    url: "/technology/woocommerce",
  },
  {
    id: 12,
    img: "/images/aws.png",
    title: "AWS",
    url: "/technology/aws",
  },
  {
    id: 13,
    img: "/images/azure.png",
    title: "Azure",
    url: "/technology/azure",
  },
  {
    id: 14,
    img: "/images/google_cloud.png",
    title: "Google Cloud",
    url: "/technology/googlecloud",
  },
  {
    id: 15,
    img: "/images/mongodb.png",
    title: "MongoDB",
    url: "/technology/mongodb",
  },
  {
    id: 16,
    img: "/images/mysql.png",
    title: "MySQL",
    url: "/technology/mysql",
  },
  {
    id: 17,
    img: "/images/sql.png",
    title: "SQLServer",
    url: "/technology/sqlserver",
  },
  {
    id: 18,
    img: "/images/postgre.png",
    title: "PostgreSQL",
    url: "/technology/postgresql",
  },
  {
    id: 19,
    img: "/images/mariadb.png",
    title: "MariaDB",
    url: "/technology/mariadb",
  },
  {
    id: 20,
    img: "/images/dynamodb.png",
    title: "DynamoDB",
    url: "/technology/dynamodb",
  },
];

export const portfolioSlider = [
  {
    id: 1,
    img: "/images/lawtendo.jpg",
    title: "Lawtendo",
    desc: "Portal / CodeIgniter",
  },
  {
    id: 2,
    img: "/images/cancri.jpg",
    title: "Cancri Jewells",
    desc: "E-Commerce / CodeIgniter",
  },
  {
    id: 3,
    img: "/images/octa.jpg",
    title: "Octa Networks",
    desc: "Education / Yii Fremwork",
  },
  {
    id: 4,
    img: "/images/attari.jpg",
    title: "Lms Attari Classes",
    desc: "Education / CodeIgniter",
  },
  {
    id: 5,
    img: "/images/geci.jpg",
    title: "Gecindia",
    desc: "Events / Wordpress",
  },
  {
    id: 6,
    img: "/images/maymart.jpg",
    title: "Maay Mart",
    desc: "Ecommerce /Laravel",
  },
];

export const industriesIcons = [
  {
    id: 1,
    img: "/images/healthcare.png",
    title: "Healthcare",
  },
  {
    id: 2,
    img: "/images/education.png",
    title: "Education",
  },
  {
    id: 3,
    img: "/images/retail.png",
    title: "Retail",
  },
  {
    id: 4,
    img: "/images/logistic.png",
    title: "Logistic",
  },
  {
    id: 5,
    img: "/images/travel.png",
    title: "Tours & Travel",
  },
  {
    id: 6,
    img: "/images/fintech.png",
    title: "FinTech",
  },
  {
    id: 7,
    img: "/images/property.png",
    title: "Real Estate",
  },
  {
    id: 8,
    img: "/images/manufacture.png",
    title: "Manufacturing",
  },
  {
    id: 9,
    img: "/images/calendar.png",
    title: "Event",
  },
  {
    id: 10,
    img: "/images/recruitment.png",
    title: "Recruitment",
  },
  {
    id: 11,
    img: "/images/flask.png",
    title: "Pharmaceutical",
  },
  {
    id: 12,
    img: "/images/service_provider.png",
    title: "Service Provider",
  },
];

export const testimonialReview = [
  {
    id: 1,
    name: "Anil Garag",
    des: '"It has been great working with Nexgeno over theyears on our website and online marketing. Theyare a great bunch of people and genuinely careabout my business and the services they areproviding me. Any issues that have come up theyhandle very professionally. I am a very happyclient. Thanks."',
  },
  {
    id: 2,
    name: "Rajesh Oberoi",
    des: ' "Working with Nexgeno technology pvt ltd on my site was such a pleasure. Arif and his team always so friendly, professional, and happy to help me with any questions and concerns about my site. I would definitely recommend her to anyone looking for a professional web designer for their project."  ',
  },
  {
    id: 3,
    name: "Rahul Garg",
    des: '"Mr Rahul Garg Sai Hospital Malad. Great experience using The Nexgeno technology pvt ltd. They have helped build a professional website and they are always happy to help should I need any alterations. Even assisted me with SEO related bits to help get my business up and running. Cannot fault the web surgery and would high recommend them."',
  },
  {
    id: 4,
    name: "Ashfaque Shaikh",
    des: '"I recently had the pleasure of working with Nexgeno Technology Pvt Ltd for my software development needs and was thoroughly impressed with the quality of their work and level of professionalism. The team was responsive, knowledgeable, and went above and beyond to ensure that my project was completed on time and within budget."',
  },
  {
    id: 5,
    name: "Tasneem Amiruddin",
    des: '"The NextGeno team is super talented, creative and very friendly. They designed my website and I was really happy with it and the entire experience. They offer you a variety of options, are very flexible and take you through the entire user experience. They have impeccable service post creating the website as well. Definitely would get back to NG for any new projects as well!"',
  },
  {
    id: 6,
    name: "Tour India Travels",
    des: '"Nexgeno Technology pvt Ltd are best website designing company in India, they help us with designing tour india company."',
  },
];

export const allServices = [
  {
    id: 1,
    title: "Web Application",
    des: "Welcome to Nexgeno Technology Pvt. Ltd, your trusted partner for web application development services in Mumbai. Our goal is to ",
    img: "/images/web_s.png",
    url: "/services/web",
  },
  {
    id: 2,
    title: "Digital Transformation",
    des: "At Nexgeno Technology Pvt Ltd, we understand the importance of digital transformation in today's business world. As technology continues",
    img: "/images/digital_s.png",
    url: "/services/digital",
  },

  {
    id: 3,
    title: "Front-end Development",
    des: "Welcome to Nexgeno Technology Pvt. Ltd, your trusted partner for front-end development services in Mumbai. We offer a wide range of front-end ",
    img: "/images/front_s.webp",
    url: "/services/frontend",
  },
  {
    id: 4,
    title: "Product Prototyping",
    des: "At Nexgeno Technology Pvt Ltd, we understand that web development and design require a robust and efficient product development process.",
    img: "/images/POS_s.jpg",
    url: "/services/product",
  },
  {
    id: 5,
    title: "Ecommerce Deployment",
    des: " At Nexgeno Technology Pvt Ltd, we understand that ecommerce is a critical part of many businesses today, and that deploying an ecommerce",
    img: "/images/e_commerce_s.png",
    url: "/services/ecommerce",
  },
  {
    id: 6,
    title: "Comprehensive Cloud",
    des: " At Nexgeno Technology Pvt Ltd, we understand the critical role that cloud computing plays in today's business environment. That's why we offer ",
    img: "/images/aws_s.png",
    url: "/services/cloud",
  },
  {
    id: 7,
    title: "Mobile App Development",
    des: "At Nexgeno Technology Pvt Ltd, we understand the importance of mobile apps in today's business landscape. With more and more people ",
    img: "/images/mobile_s.webp",
    url: "/services/mobile",
  },
  {
    id: 8,
    title: "Education/eLearning",
    des: " As mentioned earlier, Nexgeno Technology provides website designing and development services for the Education/eLearning industry, helping ",
    img: "/images/education_s.jpg",
    url: "/services/education",
  },
  {
    id: 9,
    title: "Retail Website",
    des: "For the Retail industry, Nexgeno Technology can help create a user-friendly website that showcases products, provides pricing information, ",
    img: "/images/retail_s.jpg",
    url: "/services/retail",
  },
  {
    id: 10,
    title: "Logistics & Distribution",
    des: " For the Logistics & Distribution industry, Nexgeno Technology can help create a website that provides tracking and shipment information,",
    img: "/images/logistic_s.jpg",
    url: "/services/logistics",
  },
  {
    id: 11,
    title: "FinTECH Website",
    des: "For the FinTECH industry, Nexgeno Technology can help create a website that showcases financial products and services, provides online ",
    img: "/images/fintech_s.jpg",
    url: "/services/fintech",
  },
  {
    id: 12,
    title: "Manufacturing Website",
    des: "In the Manufacturing industry, Nexgeno Technology can help create a website that showcases products, provides pricing information, ",
    img: "/images/menufac_s.jpg",
    url: "/services/manufacturing",
  },
  {
    id: 13,
    title: "Events Website",
    des: "For the Events industry, Nexgeno Technology can help create a website that showcases upcoming events, provides ticket sales functionality",
    img: "/images/event_s.jpg",
    url: "/services/events",
  },
  {
    id: 14,
    title: "Recruitment Website",
    des: "In the Recruitment industry, Nexgeno Technology can help create a website that provides job listings, allows candidates to submit ",
    img: "/images/recruitment_s.jpg",
    url: "/services/recruitment",
  },
  {
    id: 15,
    title: "Real Estate Website",
    des: "For the Real Estate industry, Nexgeno Technology can help create a website that showcases properties, provides pricing and availability ",
    img: "/images/real_s.jpg",
    url: "/services/realestate",
  },
  {
    id: 16,
    title: "Restaurants Website",
    des: "At Nexgeno Technology, we understand the unique needs of restaurants when it comes to web design and development. We offer tailored ",
    img: "/images/restaurant_s.jpg",
    url: "/services/restaurants",
  },
  {
    id: 17,
    title: "Healthcare",
    des: "In the Healthcare industry, Nexgeno Technology can help create a website that provides information on medical services, facilitates ",
    img: "/images/healthcare_s.webp",
    url: "/services/healthcare",
  },
  {
    id: 18,
    title: "Hospitality Industry",
    des: "The hospitality industry is all about providing the best experience for your guests, and that should also reflect in your online presence. At ",
    img: "/images/hospitality_s.jpg",
    url: "/services/hospitality",
  },
  {
    id: 19,
    title: "Pharmaceutical Website",
    des: "For the Pharmaceutical industry, Nexgeno Technology can help create a website that provides information on products and services,",
    img: "/images/pharma_s.jpg",
    url: "/services/pharmaceutical",
  },
  {
    id: 20,
    title: "Electronics Industry",
    des: "In the competitive world of electronics, having a professional and visually appealing website is crucial to stand out from the competition. At ",
    img: "/images/electron_s.jpg",
    url: "/services/electronics",
  },
  {
    id: 21,
    title: "Travel & Tours Website",
    des: "In the Travel & Tours industry, Nexgeno Technology can help create an engaging website that showcases destinations, attractions, ",
    img: "/images/travel_s.jpg",
    url: "/services/travel",
  },
  {
    id: 22,
    title: "Service Provider Website",
    des: "For Service Providers such as IT firms, Consultancy, and  others, Nexgeno Technology can help create a website that  showcases the ",
    img: "/images/service_s.jpg",
    url: "/services/serviceprovider",
  },
  {
    id: 23,
    title: "Hospitals Website",
    des: "Hospitals and healthcare providers require a professional and user-friendly website that not only communicates their brand and mission",
    img: "/images/hospital_s.jpg",
    url: "/services/hospitals",
  },
  {
    id: 24,
    title: "Nexgeno's Delivery Model",
    des: "Nexgeno is a leading provider of delivery model services, offering a range of solutions designed to meet the needs of businesses of all sizes. Our delivery model services are designed to help businesses streamline their operations and improve their bottom line by providing fast, efficient, and cost-effective delivery solutions.",
    img: "/images/delivery_s.svg",
    url: "/services/deliverymodel",
  },
  {
    id: 25,
    title: "Engagement Models",
    des: "At its core, an engagement model is a framework that defines the way in which a business interacts with its clients. The goal of an",
    img: "/images/engage_s.webp",
    url: "/services/engagement",
  },
  {
    id: 26,
    title: "Chatbot Services by nexgeno",
    des: "Chatbot services have become increasingly popular in recent years due to their ability to automate customer support and improve response ",
    img: "/images/chat_s.webp",
    url: "/services/chatbot",
  },
  {
    id: 27,
    title: "Demystifying AI and ML",
    des: "Artificial Intelligence (AI) and Machine Learning (ML) are buzzwords that have been increasingly used in recent years, but what exactly ",
    img: "/images/ai_s.webp",
    url: "/services/demystifying",
  },
];

export const hireDeveloper = [
  {
    id: 1,
    title: "PHP Developers",
    desc: "Looking for skilled PHP developers to join our team at Nexgeno Technology! We are a growing software development company based in Mumbai, specializing in developing custom software solutions for clients in a variety of industries.",
    img: "/images/php_h.jpg",
    url: "/hiredeveloper/php",
  },
  {
    id: 2,
    title: "Laravel Developers",
    desc: "Looking for skilled Laravel developers to join our team at Nexgeno Technology! We are a growing software development company based in Mumbai, specializing in developing custom software solutions for clients in a variety of industries.",
    img: "/images/larval_h.jpg",
    url: "/hiredeveloper/laravel",
  },
  {
    id: 3,

    title: "CodeIgniter Developers",
    desc: "Looking for skilled PHP developers with experience in CodeIgniter framework to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/codeIgniter_h.jpg",
    url: "/hiredeveloper/codeIgniter",
  },
  {
    id: 4,
    title: "ExpressJS Developers",
    desc: "Looking for skilled ExpressJS developers to join our team at Nexgeno Technology! We are a rapidly growing software development company based in Mumbai, specializing in developing custom software solutions for clients in various industries.",
    img: "/images/node_h.png",
    url: "/hiredeveloper/express",
  },
  {
    id: 5,
    title: "IOS Developers",
    desc: " Looking for skilled iOS developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/ios_h.jpg",
    url: "/hiredeveloper/ios",
  },
  {
    id: 6,
    title: "Android Developers",
    desc: " Looking for skilled Android developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/android_h.jpg",
    url: "/hiredeveloper/android",
  },
  {
    id: 7,
    title: "Flutter Developers",
    desc: "Looking for skilled Flutter developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/flutter_h.png",
    url: "/hiredeveloper/flutter",
  },
  {
    id: 8,
    title: "Angular Developers",
    desc: "Looking for skilled Angular developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/angular_h.png",
    url: "/hiredeveloper/angular",
  },
  {
    id: 9,
    title: "React Js Developers",
    desc: "Looking for skilled ReactJS developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/react_h.png",
    url: "/hiredeveloper/react",
  },
  {
    id: 10,
    title: "WordPress Developers",
    desc: "Looking for skilled WordPress developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/wordpress_h.png",
    url: "/hiredeveloper/wordpress",
  },
  {
    id: 11,
    title: "Shopify Developers",
    desc: "Looking for skilled Shopify developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/shopify_h.png",
    url: "/hiredeveloper/shopify",
  },
  {
    id: 12,
    title: "Magento Developers",
    desc: "Looking for skilled Magento developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/magento_h.png",
    url: "/hiredeveloper/magento",
  },
  {
    id: 13,
    title: "OpenCart Developers",
    desc: "Looking for skilled OpenCart developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/openchat_h.jpg",
    url: "/hiredeveloper/opencart",
  },
  {
    id: 14,
    title: "Ionic Developers",
    desc: "Looking for skilled Ionic developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
    img: "/images/iconic_h.png",
    url: "/hiredeveloper/ionic",
  },
  {
    id: 15,
    title: "React Native Developers",
    desc: "Looking for experienced React Native developers to join  Nexgeno Technology team. Strong understanding of React Native,  JavaScript, and mobile app development required. Competitive  compensation, flexible work hours, and opportunities for  professional growth and development offered. Submit your  resume and cover letter for consideration.",
    img: "/images/native_h.webp",
    url: "/hiredeveloper/reactnative",
  },
  {
    id: 16,
    title: "PWA Developers",
    desc: "Looking for skilled PWA developers to join Nexgeno Technology team. Required experience in modern web technologies, PWA development, and front-end frameworks. Bachelor's degree in Computer Science preferred. Competitive compensation, flexible work hours, and opportunities for professional growth and development offered. Submit your resume and cover letter for consideration",
    img: "/images/pws_h.svg",
    url: "/hiredeveloper/pwa",
  },
];

export const solution = [
  {
    id: 1,
    title: "School management",
    desc: "Our cloud-based school management solution streamlines all aspects of school operations, from enrollment to grade management. Say goodbye to paperwork and manual processes and hello to a modern, efficient system. Contact us today to learn more!",
    img: "/images/school_so.jpg",
    url: "/solution/school",
  },
  {
    id: 2,
    title: "Tailor Billing Application",
    desc: "Our tailor billing application streamlines billing, invoicing, and inventory management for tailors and small businesses in the fashion industry. Customizable and easy-to-use, it provides valuable insights into business performance, with detailed reporting accessible from any device",
    img: "/images/tailor_so.jpg",
    url: "/solution/tailor",
  },
  {
    id: 3,
    title: "Recruitment Billing ",
    desc: "Our cloud-based recruitment billing application simplifies billing and invoicing for staffing agencies and recruiters. It's customizable to meet the unique needs of your business and provides ongoing support from our team of experts. Say goodbye to manual billing and hello to a modern, efficient solution - contact us today!",
    img: "/images/recruitment_so.jpg",
    url: "/solution/recruitment",
  },
  {
    id: 4,
    title: "CRM Application",
    desc: "Our cloud-based CRM application provides a comprehensive solution for managing customer relationships and business operations. With customizable features and ongoing support from our team of experts, you can easily track customer interactions, manage leads, monitor sales pipelines, and analyze customer data!",
    url: "/solution/crm",
    img: "/images/crm_so.jpg",
  },
  {
    id: 5,
    title: "Billing Application",
    desc: "Our cloud-based billing application streamlines your billing process, reduces errors, and enhances efficiency. Say goodbye to manual invoicing and embrace a smarter way of billing with our cutting-edge solution.",
    img: "/images/billing_so.jpg",
    url: "/solution/billing",
  },
  {
    id: 6,
    title: "POS",
    desc: " Our cloud-based point of sale solution offers a modern and efficient way to manage your sales and inventory. Say goodbye to outdated cash registers and manual record-keeping, and hello to a smarter and more streamlined way of managing your business.",
    img: "/images/POS_s.jpg",
    url: "/solution/pos",
  },
  {
    id: 7,
    title: "Restaurant",
    desc: " Our cloud-based solution provides an efficient and easy-to-use platform for multi-restaurant management. With features like menu management, order tracking, inventory management, and real-time reporting, our solution streamlines the entire restaurant management process",
    img: "/images/restaurant_so.jpg",
    url: "/solution/restaurant",
  },
  {
    id: 8,
    title: "Car rental system",
    desc: "Streamline your car rental business with our cloud-based car rental system solution. Manage your fleet, reservations, and billing all in one place.",
    img: "/images/car_so.jpg",
    url: "/solution/car",
  },
  {
    id: 9,
    title: "Hrms payroll system",
    desc: "Simplify your HR processes with our cloud-based HRMS payroll system. Efficiently manage employee data, payroll, and benefits in one secure location.",
    img: "/images/php_h.jpg",
    url: "/solution/hrms",
  },
  {
    id: 10,
    title: "Online food ordering system",
    desc: "Our cloud-based online food ordering system offers a simple and efficient way for your customers to order and pay for their favorite dishes. Manage your restaurant operations seamlessly and enhance customer satisfaction with our cutting-edge solution.",
    img: "/images/onlinefood_so.jpg",
    url: "/solution/onlinefood",
  },
  {
    id: 11,
    title: "Hospital management system",
    desc: "Simplify your hospital management with our cloud-based solution. Streamline operations, improve patient care, and enhance decision-making.",
    img: "/images/hospital_so.jpg",
    url: "/solution/hospital",
  },
  {
    id: 12,
    title: "Job portal",
    desc: "Streamline your recruitment process and find the perfect fit for your company with our cloud-based job portal solution. Manage job postings, resumes, applications, and interviews with ease. Try it now!",
    img: "/images/job_so.jpg",
    url: "/solution/job",
  },
  {
    id: 13,
    title: "Lawyer booking solution",
    desc: "Automate your law firm's booking process and enhance your client experience with our cloud-based lawyer booking solution. Book appointments, manage schedules, and get real-time notifications on any device.",
    img: "/images/lawyer_so.jpg",
    url: "/solution/lawyer",
  },
  {
    id: 14,
    title: "Chat application",
    desc: "Boost customer support efficiency and customer satisfaction with our cloud-based chat and chatbot solution. Automate routine tasks and provide 24/7 assistance.",
    img: "/images/chat_so.jpg",
    url: "/solution/chat",
  },
  {
    id: 15,
    title: "Hotel booking system",
    desc: "Simplify your hotel management with our cloud-based booking system. Automate your operations, manage inventory, and streamline your workflow.",
    img: "/images/hotel_so.jpg",
    url: "/solution/hotel",
  },
];

export const technology = [
  {
    id: 1,
    title: "React JS",
    desc: "At Nexgeno Technology Pvt Ltd, we utilize ReactJS, an adaptable and extensible JavaScript library, to develop intuitive user interfaces. Our team comprises skilled React.js/React developers, software engineers, and programmers and collaboration.",
    img: "/images/react_t.webp",
    url: "/technology/react",
  },
  {
    id: 2,
    title: "Next js",
    desc: "At Nexgeno Technology Pvt Ltd, Next.js is a popular and powerful open-source framework for building server-rendered React applications. It is built on top of React and Node.js and provides many features to simplify and enhance the development of modern web applications.",
    img: "/images/next_t.webp",
    url: "/technology/next",
  },
  {
    id: 3,
    title: "Node js ",
    desc: "Node.js is an open-source, cross-platform JavaScript runtime environment that allows developers to build scalable, high-performance applications. It is often used for server-side programming, as well as for building command-line tools and desktop applications.",
    img: "/images/node_t.webp",
    url: "/technology/node",
  },
  {
    id: 4,
    title: "PHP ",
    desc: "PHP is a popular server-side scripting language that is used to build dynamic web applications. It is often used in conjunction with a database, such as MySQL, to create powerful web applications.",
    img: "/images/php_t.webp",
    url: "/technology/php",
  },
  {
    id: 5,
    title: "IOS",
    desc: " iOS is the operating system used by Apple's mobile devices, including the iPhone and iPad. It is known for its user-friendly interface, powerful features, and security.",
    img: "/images/ios_t.webp",
    url: "/technology/ios",
  },
  {
    id: 6,
    title: "Android",
    desc: " Android is the mobile operating system used by a variety of devices, including smartphones and tablets. It is known for its customization options, flexibility, and affordability.",
    img: "/images/android_t.webp",
    url: "/technology/android",
  },
  {
    id: 7,
    title: "Vue js",
    desc: "Nexgeno Technology is a top-notch Vue.js development company based in India, providing exceptional custom Vue.js development services. We specialize in developing real-time and dynamic applications using Vue.js, which seamlessly integrates with other JavaScript libraries",
    img: "/images/vue_t.webp",
    url: "/technology/vue",
  },
  {
    id: 8,
    title: "Google Flutter",
    desc: "Google Flutter is a framework for building native mobile applications using the Dart programming language. It allows developers to write code once and deploy it to multiple platforms, including iOS and Android.",
    img: "/images/flutter_t.jpg",
    url: "/technology/flutter",
  },
  {
    id: 9,
    title: "Wordpress",
    desc: "Wordpress is a content management system (CMS) that allows you to create and manage websites easily. It offers a wide range of plugins and themes that can be used to customize the appearance and functionality of your website. Wordpress is free to use, but you may need to pay for premium themes and plugins.",
    img: "/images/wordpress_h.png",
    url: "/technology/wordpress",
  },
  {
    id: 10,
    title: "Magento",
    desc: "Magento is an open-source e-commerce platform that allows you to create and manage online stores. It offers a wide range of features such as product management, order management, and customer management. Magento is available in both free and paid versions.",
    img: "/images/meganto_t.webp",
    url: "/technology/magento",
  },
  {
    id: 11,
    title: "Woocommerce",
    desc: "WooCommerce is a plugin for Wordpress that allows you to create and manage online stores. It offers a wide range of features such as product management, order management, and customer management. WooCommerce is free to use but may require payment for some premium features.s",
    img: "/images/wc_t.jpg",
    url: "/technology/woocommerce",
  },
  {
    id: 12,
    title: "AWS",
    desc: "AWS (Amazon Web Services) is a cloud computing platform that offers a wide range of services such as storage, computing, and analytics. It offers a pay-as-you-go pricing model and is suitable for businesses of all sizes.",
    img: "/images/aws_t.jpg",
    url: "/technology/aws",
  },
  {
    id: 13,
    title: "Azure",
    desc: "Azure is a cloud computing platform offered by Microsoft that offers a wide range of services such as storage, computing, and analytics. It offers a pay-as-you-go pricing model and is suitable for businesses of all sizes.",
    img: "/images/azure_t.jpg",
    url: "/technology/azure",
  },
  {
    id: 14,
    title: "Google",
    desc: "Google Cloud is a cloud computing platform offered by Google that provides a wide range of services for building, deploying, and managing applications and services. It offers services such as compute, storage, networking, and machine learning.",
    img: "/images/google_cloud_t.jpg",
    url: "/technology/googlecloud",
  },
  {
    id: 15,
    title: "MongoDB",
    desc: "MongoDB is a NoSQL database that provides a flexible and scalable approach to storing and managing data. It is suitable for managing large volumes of unstructured data.",
    img: "/images/mongo_t.jpg",
    url: "/technology/mongodb",
  },
  {
    id: 16,
    title: "MySQL",
    desc: " MySQL is a relational database management system (RDBMS) that is widely used for web applications. It is known for its reliability, speed, and ease of use.",
    img: "/images/mysql_t.jpg",
    url: "/technology/mysql",
  },
  {
    id: 17,
    title: "SQLServer",
    desc: "SQL Server is a relational database management system (RDBMS) developed by Microsoft. It is widely used for enterprise-level applications.",
    img: "/images/sqlserver_t.jpg",
    url: "/technology/sqlserver",
  },
  {
    id: 18,
    title: "PostgreSQL",
    desc: "PostgreSQL is a powerful, open-source relational database management system (RDBMS) that offers many advanced features. It is known for its reliability, stability, and scalability.",
    img: "/images/postgresql_t.jpg",
    url: "/technology/postgresql",
  },
  {
    id: 19,
    title: "MariaDB",
    desc: "MariaDB is an open-source relational database management system (RDBMS) that is a drop-in replacement for MySQL. It offers many advanced features and improved performance compared to MySQL.",
    img: "/images/mariaDB_t.jpg",
    url: "/technology/mariadb",
  },
  {
    id: 20,
    title: "DynamoDB",
    desc: "DynamoDB is a fully managed NoSQL database service provided by Amazon Web Services (AWS). It offers low latency and high scalability, making it suitable for applications with high traffic and large data volumes.",
    img: "/images/dyanamaDB_t.jpg",
    url: "/technology/dynamodb",
  },
];

export const industries = [
  {
    id: 1,
    link: "/industries/healthcare.htm",
    icon: "/images/healthcare.png",
    stitle: "Healthcare",
    title: "Healthcare",
    des: "In the Healthcare industry, Nexgeno Technology can help create a website that provides information on medical services, facilitates appointment booking, and allows patients to view medical records and pay bills online.",
    img: "/images/healthcare_s.webp",
    faq1: "What is web application development?",
    ans1: " Web application development is the process of creating software applications that run on a web browser. These applications are accessed over the internet and can be used on a variety of devices such as laptops, desktops, tablets, and smartphones.",
    faq2: " What technologies are used in web application development?",
    ans2: "There are many technologies used in web application development, including HTML, CSS, JavaScript, PHP, Python, Ruby, and many more. The choice of technology depends on the specific requirements of the web application and the expertise of the development team.",
  },
  {
    id: 2,
    link: "/industries/educationl-earning.htm",
    icon: "/images/education.png",
    stitle: "Education",
    title: "Education/eLearning Website Design and Development Services",
    des: " As mentioned earlier, Nexgeno Technology provides website designing and development services for the Education/eLearning industry, helping institutions create websites that serve as a central hub for course information, student communication, and eLearning resources.",
    img: "/images/education_s.jpg",
    faq1: "How can upgrading my education/eLearning website benefit my organization?",
    ans1: " Upgrading your education/eLearning website can benefit your organization by improving the user experience, making it easier for students to navigate and find the information they need. It can also help you to better showcase your courses, programs, and services, as well as increase engagement with your target audience.",
    faq2: "What kind of features can be included in an upgraded education/eLearning website?",
    ans2: "An upgraded education/eLearning website can include a range of features, such as a responsive design that works on all devices, interactive learning tools and resources, online registration and payment systems, social media integration, chatbots, and more.",
  },
  {
    id: 3,
    link: "/industries/retail.htm",
    icon: "/images/shop-bag.png",
    stitle: "Retail",
    title: "Retail Website Design and Development Services",
    des: "For the Retail industry, Nexgeno Technology can help create a user-friendly website that showcases products, provides pricing information, and makes it easy for customers to place orders and track shipments. They can also help retailers integrate payment gateways, shipping providers, and inventory management systems.",
    img: "/images/retail_s.jpg",
    faq1: "How can upgrading my retail website improve my sales and customer experience?",
    ans1: "Upgrading your retail website can improve your sales and customer experience by making it easier for customers to find products, check inventory, make purchases, and access customer support. An upgraded website can also help you to better showcase your products, promotions, and services, as well as increase engagement with your target audience.",
    faq2: "What kind of features can be included in an upgraded retail website?",
    ans2: "An upgraded retail website can include a range of features, such as a responsive design that works on all devices, intuitive navigation and search functions, user-friendly shopping carts and checkout systems, product reviews and ratings, wishlists, social media integration, and mo ",
  },
  {
    id: 4,
    link: "/industries/logistics-distribution.htm",
    icon: "/images/logistic.png",
    stitle: "Logistics",
    title: "Logistics & Distribution Website Design and Development Services",
    des: " For the Logistics & Distribution industry, Nexgeno Technology can help create a website that provides tracking and shipment information, as well as tools for managing inventory and supply chain logistics.",
    img: "/images/logistic_s.jpg",
    faq1: "How can upgrading my logistics & distribution website benefit my organization?",
    ans1: "Upgrading your logistics & distribution website can benefit your organization by improving the user experience, making it easier for customers to track shipments, check inventory, and access customer support. It can also help you to better showcase your services, as well as increase engagement with your target audience.",
    faq2: "What kind of features can be included in an upgraded logistics & distribution website?",
    ans2: " An upgraded logistics & distribution website can include a range of features, such as a responsive design that works on all devices, shipment tracking and inventory management systems, personalized recommendations, real-time notifications, customer reviews and ratings, social media integration, and mo ",
  },
  {
    id: 5,
    link: "/industries/travel-tours.htm",
    icon: "/images/travel.png",
    stitle: "Tours & Travel",
    title: "Travel & Tours Website Design and Development Services",
    des: "In the Travel & Tours industry, Nexgeno Technology can help create an engaging website that showcases destinations, attractions, and amenities. They can also help integrate booking and reservation systems, making it easy for customers to plan and book their trips online.",
    img: "/images/travel_s.jpg",
    faq1: "How can upgrading my travel & Tour website improve my bookings and customer experience?",
    ans1: "Upgrading your travel & Tour website can improve your bookings and customer experience by making it easier for customers to find and book travel and accommodation, check availability, access customer support, and leave feedback. An upgraded website can also help you to better showcase your destinations, services, and promotions, as well as increase engagement with your target audience.",
    faq2: " What kind of features can be included in an upgraded travel & Tour website?",
    ans2: "An upgraded travel & Tour website can include a range of features, such as a responsive design that works on all devices, advanced search and filter options, booking and reservation systems, personalized recommendations, interactive maps and galleries, customer reviews and ratings, social media integration, and more.",
  },
  {
    id: 6,
    link: "/industries/finTECH.htm",
    icon: "/images/online-banking.png",
    stitle: "Fintech",
    title: "FinTECH Website Design and Development Services",
    des: "For the FinTECH industry, Nexgeno Technology can help create a website that showcases financial products and services, provides online banking functionality, and integrates payment gateways and other financial tools.",
    img: "/images/fintech_s.jpg",
    faq1: "What benefits can upgrading my FinTECH company's website provide?",
    ans1: "Upgrading your FinTECH company's website can provide a number of benefits. It can improve user experience, streamline communication with clients and investors, and improve your company's online presence. A well-designed website can also help establish your company as a leader in the industry, and increase your credibility with potential clients and investors.",
    faq2: " What features should a FinTECH company consider when upgrading their website?",
    ans2: "FinTECH company should consider upgrading their website to include features that help showcase their products and services, such as interactive product demos and video tutorials. It's also important to include client testimonials and case studies, as well as detailed information about your company's expertise and team. Additionally, incorporating tools that improve website security and user privacy, such as two-factor authentication and SSL certificates, can help build trust with clients and investo ",
  },
  {
    id: 7,
    link: "/industries/real-estate.htm",
    icon: "/images/property.png",
    stitle: "Real Estate",
    title: "Real Estate Website Design and Development Services",
    des: "For the Real Estate industry, Nexgeno Technology can help create a website that showcases properties, provides pricing and availability information, and makes it easy for customers to schedule viewings and apply for rentals or mortgages.",
    img: "/images/real_s.jpg",
    faq1: "How can upgrading my real estate company's website benefit us?",
    ans1: "Upgrading your real estate company's website can provide numerous benefits, including increased visibility and credibility, improved communication with clients and stakeholders, and increased lead generation. A well-designed website can also improve the user experience for potential clients, and showcase your company's expertise and listings.",
    faq2: "What specific website features should a real estate company consider when upgrading?",
    ans2: "real estate company should consider upgrading their website to include features that improve user experience and lead generation, such as search filters for property listings, virtual tours and 3D floor plans, and an interactive map of properties for sale. It's also important to make the website mobile-responsive and user-friendly, so that potential clients can easily access information and make inquiries from their smartphones and tablets. Additionally, incorporating tools that improve website security, such as SSL certificates and secure payment gateways, can help build trust with clients and increase conversio ",
  },
  {
    id: 8,
    link: "/industries/manufacturing.htm",
    icon: "/images/manufacture.png",
    stitle: "Manufacturing",
    title: "Manufacturing Website Design and Development Services",
    des: "In the Manufacturing industry, Nexgeno Technology can help create a website that showcases products, provides pricing information, and allows customers to place orders and track shipments.",
    img: "/images/menufac_s.jpg",
    faq1: "How can upgrading my manufacturing company's website benefit us?",
    ans1: "Upgrading your manufacturing company's website can provide numerous benefits, including improved brand awareness and reputation, increased lead generation, and improved communication with customers and stakeholders. A well-designed website can also showcase your company's products and services, and highlight your industry expertise and experience.",
    faq2: "What specific website features should a manufacturing company consider when upgrading?",
    ans2: "A manufacturing company should consider upgrading their website to include features that improve user experience and lead generation, such as product catalogs with detailed specifications, online quote requests, and case studies highlighting successful projects. It's also important to make the website mobile-responsive and user-friendly, so that potential clients can easily access information and make inquiries from their smartphones and tablets. Additionally, incorporating tools that improve website security, such as SSL certificates and secure payment gateways, can help build trust with customers and increase conversio ",
  },
  {
    id: 9,
    link: "/industries/events.htm",
    icon: "/images/calendar.png",
    stitle: "Events",
    title: "Events Website Design and Development Services",
    des: "For the Events industry, Nexgeno Technology can help create a website that showcases upcoming events, provides ticket sales functionality, and allows event organizers to manage registration and logistics.",
    img: "/images/event_s.jpg",
    faq1: "How can upgrading my events company's website benefit us?",
    ans1: "Upgrading your events company's website can provide numerous benefits, including increased brand awareness and credibility, improved lead generation, and improved communication with clients and vendors. A well-designed website can also showcase your company's past events and expertise, and help establish your company as a leader in the industry.",
    faq2: "What specific website features should an events company consider when upgrading?",
    ans2: "An events company should consider upgrading their website to include features that improve user experience and lead generation, such as a portfolio of past events, event planning tools and resources, and an online event registration system. It's also important to make the website mobile-responsive and user-friendly, so that potential clients can easily access information and make inquiries from their smartphones and tablets. Additionally, incorporating tools that improve website security, such as SSL certificates and secure payment gateways, can help build trust with clients and increase conversions.",
  },
  {
    id: 10,
    link: "/industries/recruitment.htm",
    icon: "/images/recruitment.png",
    stitle: "Recruitment",
    title: "Recruitment Website Design and Development Services",
    des: "In the Recruitment industry, Nexgeno Technology can help create a website that provides job listings, allows candidates to submit applications and resumes, and facilitates communication between candidates and employers.",
    img: "/images/recruitment_s.jpg",
    faq1: " How can upgrading my recruitment company's website benefit us?",
    ans1: " Upgrading your recruitment company's website can provide numerous benefits, including increased brand awareness and credibility, improved lead generation, and improved communication with clients and job seekers. A well-designed website can also showcase your company's expertise and job opportunities, and help establish your company as a top recruitment firm in your industry.",
    faq2: "What specific website features should a recruitment company consider when upgrading?",
    ans2: "A recruitment company should consider upgrading their website to include features that improve user experience and lead generation, such as a job board with detailed job descriptions and application forms, candidate tracking tools, and resources for job seekers. It's also important to make the website mobile-responsive and user-friendly, so that potential clients and job seekers can easily access information and make inquiries from their smartphones and tablets. Additionally, incorporating tools that improve website security, such as SSL certificates and secure application forms, can help build trust with clients and increase conversio ",
  },
  {
    id: 11,
    link: "/industries/pharmaceutical.htm",
    icon: "/images/flask.png",
    stitle: "Pharmaceutical",
    title: "Pharmaceutical Website Design and Development Services",
    des: "For the Pharmaceutical industry, Nexgeno Technology can help create a website that provides information on products and services, facilitates prescription refills, and allows customers to view medical records and pay bills online.",
    img: "/images/pharma_s.jpg",
    faq1: " How can upgrading my pharmaceutical company's website benefit us?",
    ans1: "Upgrading your pharmaceutical company's website can provide numerous benefits, including increased brand awareness and credibility, improved communication with patients and healthcare professionals, and increased lead generation. A well-designed website can also showcase your company's products and services, and provide valuable information and resources for patients and healthcare professionals.",
    faq2: "What specific website features should a pharmaceutical company consider when upgrading?",
    ans2: "A pharmaceutical company should consider upgrading their website to include features that improve user experience and lead generation, such as detailed product information, online ordering and prescription refill tools, and patient resources and support programs. It's also important to make the website mobile-responsive and user-friendly, so that patients and healthcare professionals can easily access information and make inquiries from their smartphones and tablets. Additionally, incorporating tools that improve website security, such as SSL certificates and secure patient portals, can help build trust with",
  },
  {
    id: 12,
    link: "/industries/service-provider.htm",
    icon: "/images/service_provioder.png",
    stitle: "Service Provider",
    title: "Service Provider Website Design and Development Services",
    des: "For Service Providers such as IT firms, Consultancy, and  others, Nexgeno Technology can help create a website that  showcases the range of services provided, pricing, and allow  customers to contact them for services.",
    img: "/images/service_s.jpg",
    faq1: " What is web application development?",
    ans1: " Web application development is the process of creating  software applications that run on a web browser. These  applications are accessed over the internet and can be  used on a variety of devices such as laptops, desktops,  tablets, and smartphones.",
    faq2: "What technologies are used in web application development?",
    ans2: "There are many technologies used in web application  development, including HTML, CSS, JavaScript, PHP,  Python, Ruby, and many more. The choice of technology  depends on the specific requirements of the web  application and the expertise of the development team.",
  },
];
