export const items = {
  php: [
    {
      id: 1,
      title: "Hire PHP Developers",
      desc: "Looking for skilled PHP developers to join our team at Nexgeno Technology! We are a growing software development company based in Mumbai, specializing in developing custom software solutions for clients in a variety of industries.",
      img: "/images/php_h.jpg",
      faq1: "Can I hire PHP developers for full-time positions?",
      ans1: "Yes, you can hire PHP developers for full-time positions. We offer dedicated PHP developers who work exclusively on your project and provide you with regular updates and progress reports.",
      faq2: "Can your PHP developers work on existing PHP projects?",
      ans2: "Yes, our PHP developers can work on existing PHP projects. We can provide you with PHP developers who have experience in working with different PHP frameworks and can quickly understand your project requirements.",
    },
  ],
  laravel: [
    {
      id: 2,
      title: "Hire Laravel Developers",
      desc: "Looking for skilled Laravel developers to join our team at Nexgeno Technology! We are a growing software development company based in Mumbai, specializing in developing custom software solutions for clients in a variety of industries.",
      img: "/images/larval_h.jpg",
      faq1: "Why should I hire Laravel developers?",
      ans1: "Hiring Laravel developers can help you build high-quality web applications quickly and efficiently. Laravel developers have experience working with Laravel's various features and can leverage them to create scalable web applications that meet your business requirements.",
      faq2: "What kind of Laravel development services do you offer?",
      ans2: " We offer a wide range of Laravel development services, including custom Laravel development, Laravel web development, Laravel e-commerce development, Laravel CMS development, and Laravel migration servic ",
    },
  ],
  codeIgniter: [
    {
      id: 3,
      title: "Hire CodeIgniter Developers",
      desc: "Looking for skilled PHP developers with experience in CodeIgniter framework to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/codeIgniter_h.jpg",
      faq1: " Why Choose Nexgeno For Web Application Development Services?",
      ans1: "Choosing the right custom web application development company to partner with is critical to the success of your business. With so many options available, it can be difficult to know which company to trust with your web application development needs.",
      faq2: "Expertise and Experience",
      ans2: "With over [number] years of experience in web application development, our team of skilled developers has the expertise to deliver cutting-edge web solutions to businesses of all sizes and industries. We use the latest technologies and best practices to ensure that our solutions are innovative, intuitive, and secure.",
    },
  ],
  express: [
    {
      id: 4,
      title: "Hire ExpressJS Developers",
      desc: "Looking for skilled ExpressJS developers to join our team at Nexgeno Technology! We are a rapidly growing software development company based in Mumbai, specializing in developing custom software solutions for clients in various industries.",
      img: "/images/node_h.png",
      faq1: "Why should I hire ExpressJS developers?",
      ans1: "Hiring ExpressJS developers can help you build high-quality web applications quickly and efficiently. ExpressJS developers have experience working with ExpressJS's various features and can leverage them to create scalable web applications that meet your business requirements.",
      faq2: "Can I hire ExpressJS developers for full-time positions?",
      ans2: "Yes, you can hire ExpressJS developers for full-time positions. We offer dedicated ExpressJS developers who work exclusively on your project and provide you with regular updates and progress reports.",
    },
  ],

  ios: [
    {
      id: 5,
      title: "Hire IOS Developers",
      desc: " Looking for skilled iOS developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/ios_h.jpg",
      faq1: "Why should I hire iOS developers?",
      ans1: "Hiring iOS developers can help you build high-quality mobile applications for the iOS platform. iOS developers have experience working with Apple's development tools and can leverage them to create custom, native mobile apps that meet your business requirements.",
      faq2: "Can I hire iOS developers on a project basis?",
      ans2: "Yes, you can hire iOS developers on a project basis. We offer flexible engagement models to meet your specific project requireme",
    },
  ],
  android: [
    {
      id: 6,
      title: "Hire Android Developers",
      desc: " Looking for skilled Android developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/android_h.png",
      faq1: "Why Choose Nexgeno For Web Application Development Services?",
      ans1: "Choosing the right custom web application development company to partner with is critical to the success of your business. With so many options available, it can be difficult to know which to trust with your web application development needs.",
      faq2: "Expertise and Experience",
      ans2: "With over [number] years of experience in web application development, our team of skilled developers has the expertise to deliver cutting-edge web solutions to businesses of all sizes and industries. We use the latest technologies and best practices to ensure that our solutions are innovative, intuitive, and secure.",
    },
  ],
  flutter: [
    {
      id: 7,
      title: "Hire Flutter Developers",
      desc: "Looking for skilled Flutter developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/flutter_h.png",
      faq1: "Can your Flutter developers work on existing Flutter projects?",
      ans1: " Yes, our Flutter developers can work on existing Flutter projects. We can provide you with Flutter developers who have experience in working with different Flutter versions and can quickly understand your project requirements.",
      faq2: "Why should I hire Flutter developers?",
      ans2: "Hiring Flutter developers can help you build cross-platform mobile applications with a fast development cycle and high-quality user interfaces. Flutter developers have experience working with Flutter's development tools and can leverage them to create custom mobile apps that meet your business requirements.",
    },
  ],
  angular: [
    {
      id: 8,
      title: "Hire Angular Developers",
      desc: "Looking for skilled Angular developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/angular_h.png",
      faq1: " Can your Angular developers work on existing Angular projects?",
      ans1: "Yes, our Angular developers can work on existing Angular projects. We can provide you with Angular developers who have experience in working with different Angular versions and can quickly understand your project requirements.",
      faq2: " What kind of communication channels do you use to keep clients informed about project progress?",
      ans2: "We use various communication channels such as email, phone, and video conferencing to keep clients informed about project progress. We also use project management tools to provide clients with regular updates and progress reports.",
    },
  ],
  react: [
    {
      id: 9,
      title: "Hire React JS Developers",
      desc: "Looking for skilled ReactJS developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/react_h.png",
      faq1: "Can your React JS developers work on existing React projects?",
      ans1: "Yes, our React JS developers can work on existing React projects. We can provide you with React JS developers who have experience in working with different React versions and can quickly understand your project requirements.",
      faq2: "Can I hire React JS developers on a project basis?",
      ans2: "Yes, you can hire React JS developers on a project basis. We offer flexible engagement models to meet your specific project requirements.",
    },
  ],
  wordpress: [
    {
      id: 10,
      title: "Hire WordPress Developers",
      desc: "Looking for skilled WordPress developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/wordpress_h.png",
      faq1: "What is WordPress?",
      ans1: "WordPress is a free, open-source content management system (CMS) used to create websites and blogs. It is the most popular CMS in the world, powering over 40% of all websites on the internet.",
      faq2: " What kind of WordPress development services do you offer?",
      ans2: "We offer a wide range of WordPress development services, including custom WordPress theme development, WordPress plugin development, WordPress migration, WordPress e-commerce development, and WordPress maintenance and support.",
    },
  ],
  shopify: [
    {
      id: 11,
      title: "Hire Shopify Developers",
      desc: "Looking for skilled Shopify developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/shopify_h.png",
      faq1: "Why should I hire Shopify developers?",
      ans1: "Hiring Shopify developers can help you create custom Shopify stores that meet your business requirements. Shopify developers have experience working with Shopify's development tools and can leverage them to create unique and engaging online stores that help you stand out from your competitors.",
      faq2: " What is Shopify?",
      ans2: "Shopify is a popular e-commerce platform used to build online stores. It provides a range of tools and features to help businesses set up and run their online stores, including payment processing, shipping management, and inventory management.",
    },
  ],

  magento: [
    {
      id: 12,
      title: "Hire Magento Developers",
      desc: " Looking for skilled Magento developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/magento_h.png",
      faq1: "Can I hire Magento developers on a project basis?",
      ans1: "Yes, you can hire Magento developers on a project basis. We offer flexible engagement models to meet your specific project requirements.",
      faq2: "Can I hire Magento developers for full-time positions?",
      ans2: "Yes, you can hire Magento developers for full-time positions. We offer dedicated Magento developers who work exclusively on your project and provide you with regular updates and progress reports.",
    },
  ],
  opencart: [
    {
      id: 13,
      title: "Hire OpenCart Developers",
      desc: "Looking for skilled OpenCart developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/openchat_h.jpg",
      faq1: "Can I hire OpenCart developers on a project basis?",
      ans1: "Yes, you can hire OpenCart developers on a project basis. We offer flexible engagement models to meet your specific project requirements.",
      faq2: "Can I hire OpenCart developers for full-time positions?",
      ans2: "Yes, you can hire OpenCart developers for full-time positions. We offer dedicated OpenCart developers who work exclusively on your project and provide you with regular updates and progress reports.",
    },
  ],
  ionic: [
    {
      id: 14,
      title: "Hire Ionic Developers",
      desc: "Looking for skilled Ionic developers to join our team at Nexgeno Technology! We are a fast-growing software development company based in Mumbai, delivering innovative software solutions to clients across various industries.",
      img: "/images/iconic_h.png",
      faq1: "What kind of Ionic development services do you offer?",
      ans1: "We offer a wide range of Ionic development services, including custom Ionic mobile app development, Ionic UI/UX design, Ionic migration, and Ionic maintenance and support.",
      faq2: "Can I hire Ionic developers on a project basis?",
      ans2: "Yes, you can hire Ionic developers on a project basis. We offer flexible engagement models to meet your specific project requiremen ",
    },
  ],
  reactnative: [
    {
      id: 15,
      title: "Hire React Native Developers",
      desc: "Looking for experienced React Native developers to join  Nexgeno Technology team. Strong understanding of React Native,  JavaScript, and mobile app development required. Competitive  compensation, flexible work hours, and opportunities for  professional growth and development offered. Submit your  resume and cover letter for consideration.",
      img: "/images/native_h.webp",
      faq1: "Can I hire React Native developers on a project basis?",
      ans1: "Yes, you can hire React Native developers on a project  basis. We offer flexible engagement models to meet your  specific project requirements.",
      faq2: "Can I hire React Native developers for full-time  positions?",
      ans2: "Yes, you can hire React Native developers for full-time  positions. We offer dedicated React Native developers  who work exclusively on your project and provide you  with regular updates and progress reports.",
    },
  ],
  pwa: [
    {
      id: 16,
      title: "Hire PWA Developers",
      desc: "Looking for skilled PWA developers to join Nexgeno Technology team. Required experience in modern web technologies, PWA development, and front-end frameworks. Bachelor's degree in Computer Science preferred. Competitive compensation, flexible work hours, and opportunities for professional growth and development offered. Submit your resume and cover letter for consideration",
      img: "/images/pws_h.svg",
      faq1: "What kind of PWA development services do you offer?",
      ans1: " We offer a wide range of PWA development services, including custom PWA development, PWA UI/UX design, PWA migration, and PWA maintenance and support.",
      faq2: "Can I hire PWA developers on a project basis?",
      ans2: "Yes, you can hire PWA developers on a project basis. We offer flexible engagement models to meet your specific project requirements.",
    },
  ],
  next: [
    {
      id: 17,
      title: "Next js Developers",
      desc: "At Nexgeno Technology Pvt Ltd, Next.js is a popular and powerful open-source framework for building server-rendered React applications. It is built on top of React and Node.js and provides many features to simplify and enhance the development of modern web applications.",
      img: "/images/next_t.webp",
      faq1: "What is the difference between Server-Side Rendering (SSR) and Static Site Generation (SSG) in Next.js?",
      ans1: "Server-Side Rendering (SSR): With SSR, the server renders the React components on each incoming request and sends back fully rendered HTML to the client. This means that every time a user accesses a page, up-to-date information on each request.",
      faq2: "How does Next.js handle data fetching?",
      ans2: "Next.js provides multiple approaches for data fetching depending on your use case:",
    },
  ],
  vue: [
    {
      id: 18,
      title: "Hire Vue js Developers",
      desc: "Nexgeno Technology is a top-notch Vue.js development company based in India, providing exceptional custom Vue.js development services. We specialize in developing real-time and dynamic applications using Vue.js, which seamlessly integrates with other JavaScript libraries",
      img: "/images/vue_t.webp",
      faq1: "What is Vue.js?",
      ans1: "Vue.js is an open-source JavaScript framework used for building user interfaces and single-page applications. It's easy to learn, highly performant, and offers features like reactive data binding, components, and virtual DOM.",
      faq2: "Why should I choose Vue.js for my next project?",
      ans2: "Vue.js offers several advantages, including its simplicity, flexibility, and versatility. It's easy to learn, offers a small footprint, and can be integrated into existing projects. Additionally, Vue.js offers excellent performance and scalability, making it a great choice for large-scale applications.",
    },
  ],
};
